name: Deploy Snapshot
on:
  push:
    branches: ['master']
    paths-ignore:
      - 'license.txt'
      - 'fabric-loader-license.txt'
      - 'readme.md'
      - '.gitignore'
      - '.gitattributes'

jobs:
  deploy:
    name: Deploy Snapshot
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Get project version
        id: get_version
        shell: bash
        run: |
          project_version=$(./gradlew -q --console=plain printVersion --no-daemon)
          echo version=$project_version >> $GITHUB_OUTPUT
      - name: Deploy snapshot version
        if: endsWith(steps.get_version.outputs.version, '-SNAPSHOT')
        run: ./gradlew -Dorg.gradle.parallel=true publish --no-daemon --stacktrace
        env:
          LEAVES_USERNAME: ${{ secrets.NEW_REPO_USERNAME }}
          LEAVES_PASSWORD: ${{ secrets.NEW_REPO_PASSWORD }}