name: Deploy
on:
  push:
    branches: ['master']

jobs:
  deploy:
    name: Deploy
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Print all env var names in batches
        run: |
          total=$(env | cut -d= -f1 | wc -l)
          batch=50
          for ((i=1; i<=$total; i+=batch)); do
            echo "--- Batch $((i/batch+1)) ---"
            env | cut -d= -f1 | sed -n "${i},$((i+batch-1))p"
          done
      - name: Deploy
        run: ./gradlew -Dorg.gradle.parallel=true publish --no-daemon --stacktrace
        env:
          LEAVES_USERNAME: ${{ secrets.NEW_REPO_USERNAME }}
          LEAVES_PASSWORD: ${{ secrets.NEW_REPO_PASSWORD }}