name: Test
on:
  push:
    branches: [ '**' ]
  pull_request:

jobs:
  test:
    name: Test
    if: github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Execute Gradle build
        run: ./gradlew -Dorg.gradle.parallel=true test --no-daemon --stacktrace
      - name: Execute Gradle build
        run: ./gradlew -Dorg.gradle.parallel=true build --no-daemon --stacktrace